version: "3.7"
services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.3
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-enterprise-kafka:5.5.3
    depends_on: [zookeeper]
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9991
    ports:
      - 9092:9092

  ms-transaction-api:
    build:
      context: .
      dockerfile: ./ms-transaction-api/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - kafka
    environment:
      NODE_ENV: production
      PORT: 8080
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres?schema=public
      KAFKA_BROKERS: kafka:29092
      KAFKA_APPLICATION_ID: appid-transaction-api
      KAFKA_TRANSACTION_VALIDATE_TOPIC: queue-transaction-validate-stream

  ms-fraud-validation-stream:
    build:
      context: .
      dockerfile: ./ms-fraud-validation-stream/Dockerfile
    depends_on:
      - postgres
      - kafka
      - ms-transaction-api
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres?schema=public
      KAFKA_BROKERS: kafka:29092
      KAFKA_APPLICATION_ID: appid-transaction-api
      KAFKA_APPLICATION_GROUP: group-transaction-api
      KAFKA_TRANSACTION_VALIDATE_TOPIC: queue-transaction-validate-stream
